const fs=require('fs');
const path=require('path');
const vm=require('vm');
const assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length);
const refs=[...html.matchAll(/\$\('([^']+)'\)/g)].map(m=>m[1]);
assert.deepEqual([...new Set(refs.filter(id=>!ids.includes(id)))],[]);
const elements=new Map();
const drawing={setTransform(){},clearRect(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},fillText(){},drawImage(){},putImageData(){},createImageData(w,h){return {width:w,height:h,data:new Uint8ClampedArray(w*h*4)};}};
function element(id){if(elements.has(id))return elements.get(id);const classes=new Set();const el={id,value:'',checked:false,disabled:false,hidden:false,textContent:'',innerHTML:'',style:{},dataset:{},attrs:{},handlers:{},clientWidth:320,clientHeight:190,width:320,height:190,classList:{add(...x){x.forEach(c=>classes.add(c));},remove(...x){x.forEach(c=>classes.delete(c));},contains(c){return classes.has(c);},toggle(c,on){on===undefined?classes.has(c)?classes.delete(c):classes.add(c):on?classes.add(c):classes.delete(c);}},addEventListener(event,fn){this.handlers[event]=fn;},setAttribute(k,v){this.attrs[k]=v;},getContext(){return drawing;},matches(){return false;},scrollIntoView(){},requestFullscreen(){return Promise.resolve();}};elements.set(id,el);return el;}
ids.forEach(element);
for(const id of ['start','stop','inspect-bytes'])element(id).disabled=true;
for(const [id,value] of Object.entries({frequency:'1600',lna:'16',vga:'16',span:'0',floor:'-100',ceiling:'-15'}))element(id).value=value;
const tabs=['bits','hex','ascii'].map(v=>{const e=element('format-'+v);e.dataset.format=v;return e;});
const presets=['433.92','915','1090','1600'].map(v=>{const e=element('preset-'+v);e.dataset.frequency=v;return e;});
const document={body:{dataset:{}},documentElement:element('document-root'),activeElement:null,fullscreenElement:null,getElementById:element,querySelector(s){return element(s);},querySelectorAll(s){return s==='[data-format]'?tabs:s==='[data-frequency]'?presets:[];},addEventListener(){},createElement(){return element('offscreen');},exitFullscreen(){return Promise.resolve();}};
let reply=null;
const emitted=[];
const context=vm.createContext({document,window:{location:{search:'?screen=analysis'},devicePixelRatio:1,addEventListener(){},dispatchEvent(e){emitted.push(e);},open(){return {}; }},URLSearchParams,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},fetch(){return reply===null?new Promise(()=>{}):Promise.resolve({ok:true,json:()=>Promise.resolve(reply)});},AbortController,setTimeout(){return 1;},clearTimeout(){},setInterval(){return 1;},clearInterval(){},atob:v=>Buffer.from(v,'base64').toString('binary'),Uint8Array,Uint8ClampedArray,Date,console});
vm.runInContext(script,context);
let checks=3;
function check(expression,message){assert.equal(vm.runInContext(expression,context),true,message);checks++;}
check("document.body.dataset.screen==='analysis'",'analysis workspace selected');
check("$('start').disabled",'startup has no radio start');
check("$('power').innerHTML==='—<span class=\"unit\">dBFS</span>' || $('power').innerHTML===''",'no fabricated power');
context.status={application_name:'Anomaly SDR Studio',version:'0.1.0',mode:'idle',state:'stopped',device:{available:false},config:{sample_rate:8000000,frequency_hz:1600000000,symbol_rate:null},rx:{power_dbfs:null,samples_received:0},analysis:null,decoded:[]};
vm.runInContext('renderStatus(status)',context);
check("$('power').innerHTML.startsWith('—')",'null power remains unavailable');
check("$('candidate-count').textContent==='—'",'no analysis is not zero candidates');
check("$('baseline-score').textContent==='—'",'baseline unavailable');
check("$('structure-score').innerHTML.startsWith('—')",'structure unavailable');
context.analysis={baseline:{state:'warming',cold_start:true,frames:2,warmup_frames:20,anomaly_score:0},spectrum:{fft_size:8192,bin_width_hz:976.5625,power_db:Array(8192).fill(-80)},metrics:{power_dbfs:-36},candidates:[{id:'c1',center_hz:1600100000,offset_hz:100000,bandwidth_hz:12000,snr_db:22,anomaly_score:0,persistence_frames:3,modulation:{suggestions:[{name:'FSK',confidence:'low',reason:'Two phase clusters'}]},decode:{state:'candidate-bits',bits:'0100000101000010',verified:false}}],visuals:{},structure:{state:'measured',structure_score:70,samples_analyzed:16384,window_duration_seconds:.002,metrics:{spectral_flatness:.02,normalized_spectral_entropy:.2,complex_autocorrelation_peak:.8,complex_autocorrelation_lag_seconds:.00001,periodicity_peak:.5,periodicity_hz:8000,amplitude_excess_kurtosis:.9,i_q_correlation:.2},flags:[{label:'Repeated envelope',evidence:'periodic'}]},demodulation:{candidate_id:'c1',am:{envelope:[.1,.2,.1]},fm:{frequency_hz:[100,200,100]}}};
context.status={...context.status,mode:'demo',state:'receiving',analysis:context.analysis,candidates:context.analysis.candidates,decoded:[{crc_valid:false,verified:true,text:'MUST NOT CONFIRM'},{crc_valid:true,synthetic:true,source_mode:'demo',packet:{payload_text:'ASDR-LAB|v1|...'}}],events:[{time:'2026-10-03T18:00:00Z',message:'<script>alert(1)</script>'}],recognition:{capabilities:[{label:'rtl_433',status:'ready'}],packets:[{crc_valid:false,protocol:'Generic candidate',text:'<iframe>'}]} };
vm.runInContext('renderStatus(status)',context);
check("$('source-title').textContent.includes('SYNTHETIC')",'synthetic mode conspicuous');
check("$('baseline-score').textContent==='—'",'warming score never measured zero');
check("$('candidate-rows').innerHTML.includes('warming')",'candidate anomaly warms up');
check("$('structure-score').innerHTML.startsWith('70')",'structure measured independently');
check("$('decode-caption').textContent.includes('Unvalidated')",'bits explicitly unvalidated');
check("$('decode-text').textContent==='01000001 01000010'",'actual bits displayed');
check("!$('inspect-bytes').disabled",'candidate byte inspection available');
check("!$('decoded').innerHTML.includes('MUST NOT CONFIRM')",'generic verified flag insufficient for CRC timeline');
check("$('decoded').innerHTML.includes('SYNTHETIC DEMO')",'synthetic validated protocol frame source retained');
check("$('events').innerHTML.includes('&lt;script&gt;')",'event text escaped');
check("$('recognition-packets').innerHTML.includes('&lt;iframe&gt;')",'recognition payload escaped');
vm.runInContext("app.format='ascii'; renderCandidates()",context);
check("$('decode-text').textContent==='AB'",'ASCII preview derived from explicit candidate bits');
vm.runInContext("$('inspect-bytes').handlers.click()",context);
const payloadEvent=emitted.find(e=>e.type==='anomaly-sdr-payload');
assert.equal(payloadEvent.type,'anomaly-sdr-payload');checks++;
assert.equal(payloadEvent.detail.hex,'4142');checks++;
assert(payloadEvent.detail.label.includes('UNVALIDATED'));checks++;
assert(emitted.some(e=>e.type==='anomaly-sdr-status'));checks++;
context.analysis.baseline={state:'ready',cold_start:false,frames:30,warmup_frames:20,anomaly_score:0};
vm.runInContext('renderStatus(status)',context);
check("$('baseline-score').textContent==='0'",'measured stable novelty can be zero');
check("$('structure-score').innerHTML.startsWith('70')",'learned stability does not erase raw structure');
context.status={...context.status,mode:'live',state:'receiving',analysis:null,candidates:[],events:[],decoded:[],device:{available:true}};
vm.runInContext('renderStatus(status)',context);
check("$('source-title').textContent.includes('RECEIVER SAMPLES')",'live samples label distinct');
check("$('decode-text').textContent.includes('No candidate')",'mode switch clears interpretation');
check("$('start').disabled",'active receiver cannot start twice');
check("$('frequency').disabled",'active tuning locked');
context.waterfallReply={epoch:'test',latest_sequence:799,fft_size:8192,sample_rate:8000000,frequency_hz:1600000000,floor_db:-120,ceiling_db:0,rows:Array.from({length:800},(_,sequence)=>({sequence,time:Date.now()/1000,power_u8:Buffer.alloc(8192,90).toString('base64')}))};
(async()=>{reply=context.waterfallReply;vm.runInContext('app.waterBusy=false',context);await vm.runInContext('pollWaterfall()',context);check('app.history.length===600','history bound');check('app.since===799','incremental sequence tracked');reply={closed:false};await vm.runInContext("$('quit').handlers.click()",context);check('!app.closed','unconfirmed quit keeps app alive');check("$('error-box').textContent.includes('Shutdown unconfirmed')",'shutdown error visible');reply={closed:true};await vm.runInContext("$('quit').handlers.click()",context);check('app.closed','confirmed quit closes');check("$('closed-layer').classList.contains('visible')",'closed receipt visible');console.log(JSON.stringify({result:'PASS',checks,script:'actual index.html JavaScript',hardware:'none',browser:'DOM/canvas harness'},null,2));})().catch(error=>{console.error(error);process.exitCode=1;});
